[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."send-reminders"]
  schedule = "0 * * * *"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
